In [1]:
import numpy as np

5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.

In [25]:
a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
a1 = a.reshape(12, 1)
print(a1)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [33]:
a2 = a1.T
print(a2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [35]:
print(a1.shape)
print(a2.shape)

(12, 1)
(1, 12)


In [44]:
c = np.add(a1, a2)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 2  3  4  5  6  7  8  9 10 11 12 13]
 [ 3  4  5  6  7  8  9 10 11 12 13 14]
 [ 4  5  6  7  8  9 10 11 12 13 14 15]
 [ 5  6  7  8  9 10 11 12 13 14 15 16]
 [ 6  7  8  9 10 11 12 13 14 15 16 17]
 [ 7  8  9 10 11 12 13 14 15 16 17 18]
 [ 8  9 10 11 12 13 14 15 16 17 18 19]
 [ 9 10 11 12 13 14 15 16 17 18 19 20]
 [10 11 12 13 14 15 16 17 18 19 20 21]
 [11 12 13 14 15 16 17 18 19 20 21 22]]


In [48]:
c1 = np.add(a2, a1)
print(c1)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 2  3  4  5  6  7  8  9 10 11 12 13]
 [ 3  4  5  6  7  8  9 10 11 12 13 14]
 [ 4  5  6  7  8  9 10 11 12 13 14 15]
 [ 5  6  7  8  9 10 11 12 13 14 15 16]
 [ 6  7  8  9 10 11 12 13 14 15 16 17]
 [ 7  8  9 10 11 12 13 14 15 16 17 18]
 [ 8  9 10 11 12 13 14 15 16 17 18 19]
 [ 9 10 11 12 13 14 15 16 17 18 19 20]
 [10 11 12 13 14 15 16 17 18 19 20 21]
 [11 12 13 14 15 16 17 18 19 20 21 22]]


In [49]:
c2 = np.subtract(a1, a2)
print(c2)

[[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]
 [  1   0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
 [  2   1   0  -1  -2  -3  -4  -5  -6  -7  -8  -9]
 [  3   2   1   0  -1  -2  -3  -4  -5  -6  -7  -8]
 [  4   3   2   1   0  -1  -2  -3  -4  -5  -6  -7]
 [  5   4   3   2   1   0  -1  -2  -3  -4  -5  -6]
 [  6   5   4   3   2   1   0  -1  -2  -3  -4  -5]
 [  7   6   5   4   3   2   1   0  -1  -2  -3  -4]
 [  8   7   6   5   4   3   2   1   0  -1  -2  -3]
 [  9   8   7   6   5   4   3   2   1   0  -1  -2]
 [ 10   9   8   7   6   5   4   3   2   1   0  -1]
 [ 11  10   9   8   7   6   5   4   3   2   1   0]]


In [50]:
c3 = np.subtract(a2, a1)
print(c3)

[[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ -1   0   1   2   3   4   5   6   7   8   9  10]
 [ -2  -1   0   1   2   3   4   5   6   7   8   9]
 [ -3  -2  -1   0   1   2   3   4   5   6   7   8]
 [ -4  -3  -2  -1   0   1   2   3   4   5   6   7]
 [ -5  -4  -3  -2  -1   0   1   2   3   4   5   6]
 [ -6  -5  -4  -3  -2  -1   0   1   2   3   4   5]
 [ -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4]
 [ -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3]
 [ -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2]
 [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1]
 [-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0]]


In [51]:
c4 = np.dot(a1, a2)
print(c4)

[[  0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   2   3   4   5   6   7   8   9  10  11]
 [  0   2   4   6   8  10  12  14  16  18  20  22]
 [  0   3   6   9  12  15  18  21  24  27  30  33]
 [  0   4   8  12  16  20  24  28  32  36  40  44]
 [  0   5  10  15  20  25  30  35  40  45  50  55]
 [  0   6  12  18  24  30  36  42  48  54  60  66]
 [  0   7  14  21  28  35  42  49  56  63  70  77]
 [  0   8  16  24  32  40  48  56  64  72  80  88]
 [  0   9  18  27  36  45  54  63  72  81  90  99]
 [  0  10  20  30  40  50  60  70  80  90 100 110]
 [  0  11  22  33  44  55  66  77  88  99 110 121]]


In [52]:
c5 = np.dot(a2, a1)
print(c5)

[[506]]


Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.
E = 1/5

5.2.
Вычислите определитель:


In [61]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]], float)
print(a)

[[1. 2. 3.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [55]:
det1 = np.linalg.det(a)
print(det1)

59.999999999999986


In [56]:
det2 = (1*(0*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 0*7))
print(det2)

60


5.3 - 1. Вычислите матрицу, обратную данной:

In [62]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [64]:
a_inv = np.linalg.inv(a)
print(a_inv)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


2. Приведите пример матрицы 4х4, ранг которой равен 1.

Матрица размера 4х4, ранг которой будет равен 1, будет состоять из чисел в строках которй все элементы будут равны, а11 = а12 = 
а13 = а14, а элементы следующих строк будут отличать ся на 1. а21 = а11+1, а22 = а12 +1, а23 = а13+1, а24 = а14+1;
а31 = а21+1, а32 = а22+1, а33 = а23+1, а34 = а24 +1; а41 = а31+1, а42 = а32+1, а43 = а33 +1, а44 = а34+1;

In [82]:
a = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3], [4,4,4,4]])
b = np.array([[2,2,2,2], [3,3,3,3], [4,4,4,4], [5,5,5,5]])
c = np.array([[3,3,3,3], [4,4,4,4], [5,5,5,5], [6,6,6,6]])
print(a);
print(b);
print(c)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
[[2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
[[3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


5.4. Вычислите скалярное произведение двух векторов:  (1, 5)  и  (2, 8)

In [67]:
a = np.array([1, 5])
b = np.array([2, 8])
print(a)
print(b)

[1 5]
[2 8]


In [77]:
s = np.inner(a, b)
s/(np.linalg.norm(a)*np.linalg.norm(b))

0.7614996105085897

5.5 Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [75]:
a = np.array([1, 5, 0], float)
b = np.array([2, 8, 7], float)
c = np.array([7, 1.5, 3])

print(a)
print(b)
print(c)

[1. 5. 0.]
[2. 8. 7.]
[7.  1.5 3. ]


In [76]:
v = np.cross(a, b)
print (np.inner(v, c))
w = np.cross(b, c)
print (np.inner(w, a))

228.5
228.5
